### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fcurella** [zacchiro/costituzione#11]
Could you please add a license? I don't really care which one you pick, just add one so the code is not 'all rights reserved' :)

**Comment by zacchiro** [comment]
On Fri, Sep 09, 2016 at 08:30:44AM -0700, Flavio Curella wrote:

> Could you please add a license? I don't really care which one you
> pick, just add one so the code is not 'all rights reserved' :)

This is now done.

I have delayed this only because I hadn't yet took the time to figure
out the source documenting that the texts of the Italian constitutions
are in the Public Domain. I've now done so, see top-level LICENSE file.

Thanks for your bug report,

## Cheers.

Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »
